#!/bin/sh
# Wrapper to launch MangoHud Profile Manager with the correct Python path
export PYTHONPATH=$PYTHONPATH:/app/lib/python3.12/site-packages:/app/lib/python3.13/site-packages
exec python3 /app/lib/mangomanager/mangomanager.py "$@"
